[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  path = "/forms/*"
  function = "forms-gate"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/cap/:splat"
  status = 200

